/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTherapistRouteImport } from './routes/dashboard.therapist'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStoryRouteImport } from './routes/dashboard.story'
import { Route as DashboardSimulationRouteImport } from './routes/dashboard.simulation'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard.resources'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as DashboardJourneyRouteImport } from './routes/dashboard.journey'
import { Route as DashboardEmotionRouteImport } from './routes/dashboard.emotion'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as ApiDataActionRouteImport } from './routes/api/data/$action'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTherapistRoute = DashboardTherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoryRoute = DashboardStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJourneyRoute = DashboardJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmotionRoute = DashboardEmotionRouteImport.update({
  id: '/emotion',
  path: '/emotion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiDataActionRoute = ApiDataActionRouteImport.update({
  id: '/api/data/$action',
  path: '/api/data/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/emotion': typeof DashboardEmotionRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/story': typeof DashboardStoryRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/therapist': typeof DashboardTherapistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/emotion': typeof DashboardEmotionRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/story': typeof DashboardStoryRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/therapist': typeof DashboardTherapistRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/emotion': typeof DashboardEmotionRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/story': typeof DashboardStoryRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/therapist': typeof DashboardTherapistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/achievements'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/emotion'
    | '/dashboard/journey'
    | '/dashboard/parent'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/story'
    | '/dashboard/teacher'
    | '/dashboard/therapist'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/achievements'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/emotion'
    | '/dashboard/journey'
    | '/dashboard/parent'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/story'
    | '/dashboard/teacher'
    | '/dashboard/therapist'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/achievements'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/emotion'
    | '/dashboard/journey'
    | '/dashboard/parent'
    | '/dashboard/resources'
    | '/dashboard/settings'
    | '/dashboard/simulation'
    | '/dashboard/story'
    | '/dashboard/teacher'
    | '/dashboard/therapist'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDataActionRoute: typeof ApiDataActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/therapist': {
      id: '/dashboard/therapist'
      path: '/therapist'
      fullPath: '/dashboard/therapist'
      preLoaderRoute: typeof DashboardTherapistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/story': {
      id: '/dashboard/story'
      path: '/story'
      fullPath: '/dashboard/story'
      preLoaderRoute: typeof DashboardStoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulation': {
      id: '/dashboard/simulation'
      path: '/simulation'
      fullPath: '/dashboard/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journey': {
      id: '/dashboard/journey'
      path: '/journey'
      fullPath: '/dashboard/journey'
      preLoaderRoute: typeof DashboardJourneyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emotion': {
      id: '/dashboard/emotion'
      path: '/emotion'
      fullPath: '/dashboard/emotion'
      preLoaderRoute: typeof DashboardEmotionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/data/$action': {
      id: '/api/data/$action'
      path: '/api/data/$action'
      fullPath: '/api/data/$action'
      preLoaderRoute: typeof ApiDataActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardEmotionRoute: typeof DashboardEmotionRoute
  DashboardJourneyRoute: typeof DashboardJourneyRoute
  DashboardParentRoute: typeof DashboardParentRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
  DashboardStoryRoute: typeof DashboardStoryRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardTherapistRoute: typeof DashboardTherapistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardEmotionRoute: DashboardEmotionRoute,
  DashboardJourneyRoute: DashboardJourneyRoute,
  DashboardParentRoute: DashboardParentRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
  DashboardStoryRoute: DashboardStoryRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardTherapistRoute: DashboardTherapistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDataActionRoute: ApiDataActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
