/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTherapistIndexRouteImport } from './routes/dashboard/therapist/index'
import { Route as DashboardTeacherIndexRouteImport } from './routes/dashboard/teacher/index'
import { Route as DashboardParentIndexRouteImport } from './routes/dashboard/parent/index'
import { Route as DashboardTherapistSessionsRouteImport } from './routes/dashboard/therapist/sessions'
import { Route as DashboardTherapistResourcesRouteImport } from './routes/dashboard/therapist/resources'
import { Route as DashboardTherapistReportRouteImport } from './routes/dashboard/therapist/report'
import { Route as DashboardTherapistAnalyticsRouteImport } from './routes/dashboard/therapist/analytics'
import { Route as DashboardTeacherResourcesRouteImport } from './routes/dashboard/teacher/resources'
import { Route as DashboardTeacherReportRouteImport } from './routes/dashboard/teacher/report'
import { Route as DashboardTeacherObservationsRouteImport } from './routes/dashboard/teacher/observations'
import { Route as DashboardTeacherAnalyticsRouteImport } from './routes/dashboard/teacher/analytics'
import { Route as DashboardSharedSettingsRouteImport } from './routes/dashboard/shared/settings'
import { Route as DashboardSharedCommunityRouteImport } from './routes/dashboard/shared/community'
import { Route as DashboardParentResourcesRouteImport } from './routes/dashboard/parent/resources'
import { Route as DashboardParentReportRouteImport } from './routes/dashboard/parent/report'
import { Route as DashboardParentChildrenRouteImport } from './routes/dashboard/parent/children'
import { Route as DashboardParentAnalyticsRouteImport } from './routes/dashboard/parent/analytics'
import { Route as DashboardChildStoryRouteImport } from './routes/dashboard/child/story'
import { Route as DashboardChildSimulationRouteImport } from './routes/dashboard/child/simulation'
import { Route as DashboardChildMissionRouteImport } from './routes/dashboard/child/mission'
import { Route as DashboardChildJourneyRouteImport } from './routes/dashboard/child/journey'
import { Route as DashboardChildEmotionRouteImport } from './routes/dashboard/child/emotion'
import { Route as DashboardChildAchievementsRouteImport } from './routes/dashboard/child/achievements'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminResourcesRouteImport } from './routes/dashboard/admin/resources'
import { Route as DashboardAdminCommunityRouteImport } from './routes/dashboard/admin/community'
import { Route as ApiDataActionRouteImport } from './routes/api/data/$action'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTherapistIndexRoute = DashboardTherapistIndexRouteImport.update({
  id: '/therapist/',
  path: '/therapist/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeacherIndexRoute = DashboardTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardParentIndexRoute = DashboardParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTherapistSessionsRoute =
  DashboardTherapistSessionsRouteImport.update({
    id: '/therapist/sessions',
    path: '/therapist/sessions',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTherapistResourcesRoute =
  DashboardTherapistResourcesRouteImport.update({
    id: '/therapist/resources',
    path: '/therapist/resources',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTherapistReportRoute =
  DashboardTherapistReportRouteImport.update({
    id: '/therapist/report',
    path: '/therapist/report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTherapistAnalyticsRoute =
  DashboardTherapistAnalyticsRouteImport.update({
    id: '/therapist/analytics',
    path: '/therapist/analytics',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTeacherResourcesRoute =
  DashboardTeacherResourcesRouteImport.update({
    id: '/teacher/resources',
    path: '/teacher/resources',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTeacherReportRoute = DashboardTeacherReportRouteImport.update({
  id: '/teacher/report',
  path: '/teacher/report',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeacherObservationsRoute =
  DashboardTeacherObservationsRouteImport.update({
    id: '/teacher/observations',
    path: '/teacher/observations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTeacherAnalyticsRoute =
  DashboardTeacherAnalyticsRouteImport.update({
    id: '/teacher/analytics',
    path: '/teacher/analytics',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSharedSettingsRoute = DashboardSharedSettingsRouteImport.update({
  id: '/shared/settings',
  path: '/shared/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSharedCommunityRoute =
  DashboardSharedCommunityRouteImport.update({
    id: '/shared/community',
    path: '/shared/community',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardParentResourcesRoute =
  DashboardParentResourcesRouteImport.update({
    id: '/parent/resources',
    path: '/parent/resources',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardParentReportRoute = DashboardParentReportRouteImport.update({
  id: '/parent/report',
  path: '/parent/report',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardParentChildrenRoute = DashboardParentChildrenRouteImport.update({
  id: '/parent/children',
  path: '/parent/children',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardParentAnalyticsRoute =
  DashboardParentAnalyticsRouteImport.update({
    id: '/parent/analytics',
    path: '/parent/analytics',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChildStoryRoute = DashboardChildStoryRouteImport.update({
  id: '/child/story',
  path: '/child/story',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChildSimulationRoute =
  DashboardChildSimulationRouteImport.update({
    id: '/child/simulation',
    path: '/child/simulation',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChildMissionRoute = DashboardChildMissionRouteImport.update({
  id: '/child/mission',
  path: '/child/mission',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChildJourneyRoute = DashboardChildJourneyRouteImport.update({
  id: '/child/journey',
  path: '/child/journey',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChildEmotionRoute = DashboardChildEmotionRouteImport.update({
  id: '/child/emotion',
  path: '/child/emotion',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChildAchievementsRoute =
  DashboardChildAchievementsRouteImport.update({
    id: '/child/achievements',
    path: '/child/achievements',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminResourcesRoute = DashboardAdminResourcesRouteImport.update({
  id: '/admin/resources',
  path: '/admin/resources',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminCommunityRoute = DashboardAdminCommunityRouteImport.update({
  id: '/admin/community',
  path: '/admin/community',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiDataActionRoute = ApiDataActionRouteImport.update({
  id: '/api/data/$action',
  path: '/api/data/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
  '/dashboard/admin/community': typeof DashboardAdminCommunityRoute
  '/dashboard/admin/resources': typeof DashboardAdminResourcesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/child/achievements': typeof DashboardChildAchievementsRoute
  '/dashboard/child/emotion': typeof DashboardChildEmotionRoute
  '/dashboard/child/journey': typeof DashboardChildJourneyRoute
  '/dashboard/child/mission': typeof DashboardChildMissionRoute
  '/dashboard/child/simulation': typeof DashboardChildSimulationRoute
  '/dashboard/child/story': typeof DashboardChildStoryRoute
  '/dashboard/parent/analytics': typeof DashboardParentAnalyticsRoute
  '/dashboard/parent/children': typeof DashboardParentChildrenRoute
  '/dashboard/parent/report': typeof DashboardParentReportRoute
  '/dashboard/parent/resources': typeof DashboardParentResourcesRoute
  '/dashboard/shared/community': typeof DashboardSharedCommunityRoute
  '/dashboard/shared/settings': typeof DashboardSharedSettingsRoute
  '/dashboard/teacher/analytics': typeof DashboardTeacherAnalyticsRoute
  '/dashboard/teacher/observations': typeof DashboardTeacherObservationsRoute
  '/dashboard/teacher/report': typeof DashboardTeacherReportRoute
  '/dashboard/teacher/resources': typeof DashboardTeacherResourcesRoute
  '/dashboard/therapist/analytics': typeof DashboardTherapistAnalyticsRoute
  '/dashboard/therapist/report': typeof DashboardTherapistReportRoute
  '/dashboard/therapist/resources': typeof DashboardTherapistResourcesRoute
  '/dashboard/therapist/sessions': typeof DashboardTherapistSessionsRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/therapist/': typeof DashboardTherapistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
  '/dashboard/admin/community': typeof DashboardAdminCommunityRoute
  '/dashboard/admin/resources': typeof DashboardAdminResourcesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/child/achievements': typeof DashboardChildAchievementsRoute
  '/dashboard/child/emotion': typeof DashboardChildEmotionRoute
  '/dashboard/child/journey': typeof DashboardChildJourneyRoute
  '/dashboard/child/mission': typeof DashboardChildMissionRoute
  '/dashboard/child/simulation': typeof DashboardChildSimulationRoute
  '/dashboard/child/story': typeof DashboardChildStoryRoute
  '/dashboard/parent/analytics': typeof DashboardParentAnalyticsRoute
  '/dashboard/parent/children': typeof DashboardParentChildrenRoute
  '/dashboard/parent/report': typeof DashboardParentReportRoute
  '/dashboard/parent/resources': typeof DashboardParentResourcesRoute
  '/dashboard/shared/community': typeof DashboardSharedCommunityRoute
  '/dashboard/shared/settings': typeof DashboardSharedSettingsRoute
  '/dashboard/teacher/analytics': typeof DashboardTeacherAnalyticsRoute
  '/dashboard/teacher/observations': typeof DashboardTeacherObservationsRoute
  '/dashboard/teacher/report': typeof DashboardTeacherReportRoute
  '/dashboard/teacher/resources': typeof DashboardTeacherResourcesRoute
  '/dashboard/therapist/analytics': typeof DashboardTherapistAnalyticsRoute
  '/dashboard/therapist/report': typeof DashboardTherapistReportRoute
  '/dashboard/therapist/resources': typeof DashboardTherapistResourcesRoute
  '/dashboard/therapist/sessions': typeof DashboardTherapistSessionsRoute
  '/dashboard/parent': typeof DashboardParentIndexRoute
  '/dashboard/teacher': typeof DashboardTeacherIndexRoute
  '/dashboard/therapist': typeof DashboardTherapistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/data/$action': typeof ApiDataActionRoute
  '/dashboard/admin/community': typeof DashboardAdminCommunityRoute
  '/dashboard/admin/resources': typeof DashboardAdminResourcesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/child/achievements': typeof DashboardChildAchievementsRoute
  '/dashboard/child/emotion': typeof DashboardChildEmotionRoute
  '/dashboard/child/journey': typeof DashboardChildJourneyRoute
  '/dashboard/child/mission': typeof DashboardChildMissionRoute
  '/dashboard/child/simulation': typeof DashboardChildSimulationRoute
  '/dashboard/child/story': typeof DashboardChildStoryRoute
  '/dashboard/parent/analytics': typeof DashboardParentAnalyticsRoute
  '/dashboard/parent/children': typeof DashboardParentChildrenRoute
  '/dashboard/parent/report': typeof DashboardParentReportRoute
  '/dashboard/parent/resources': typeof DashboardParentResourcesRoute
  '/dashboard/shared/community': typeof DashboardSharedCommunityRoute
  '/dashboard/shared/settings': typeof DashboardSharedSettingsRoute
  '/dashboard/teacher/analytics': typeof DashboardTeacherAnalyticsRoute
  '/dashboard/teacher/observations': typeof DashboardTeacherObservationsRoute
  '/dashboard/teacher/report': typeof DashboardTeacherReportRoute
  '/dashboard/teacher/resources': typeof DashboardTeacherResourcesRoute
  '/dashboard/therapist/analytics': typeof DashboardTherapistAnalyticsRoute
  '/dashboard/therapist/report': typeof DashboardTherapistReportRoute
  '/dashboard/therapist/resources': typeof DashboardTherapistResourcesRoute
  '/dashboard/therapist/sessions': typeof DashboardTherapistSessionsRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/therapist/': typeof DashboardTherapistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
    | '/dashboard/admin/community'
    | '/dashboard/admin/resources'
    | '/dashboard/admin/users'
    | '/dashboard/child/achievements'
    | '/dashboard/child/emotion'
    | '/dashboard/child/journey'
    | '/dashboard/child/mission'
    | '/dashboard/child/simulation'
    | '/dashboard/child/story'
    | '/dashboard/parent/analytics'
    | '/dashboard/parent/children'
    | '/dashboard/parent/report'
    | '/dashboard/parent/resources'
    | '/dashboard/shared/community'
    | '/dashboard/shared/settings'
    | '/dashboard/teacher/analytics'
    | '/dashboard/teacher/observations'
    | '/dashboard/teacher/report'
    | '/dashboard/teacher/resources'
    | '/dashboard/therapist/analytics'
    | '/dashboard/therapist/report'
    | '/dashboard/therapist/resources'
    | '/dashboard/therapist/sessions'
    | '/dashboard/parent/'
    | '/dashboard/teacher/'
    | '/dashboard/therapist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
    | '/dashboard/admin/community'
    | '/dashboard/admin/resources'
    | '/dashboard/admin/users'
    | '/dashboard/child/achievements'
    | '/dashboard/child/emotion'
    | '/dashboard/child/journey'
    | '/dashboard/child/mission'
    | '/dashboard/child/simulation'
    | '/dashboard/child/story'
    | '/dashboard/parent/analytics'
    | '/dashboard/parent/children'
    | '/dashboard/parent/report'
    | '/dashboard/parent/resources'
    | '/dashboard/shared/community'
    | '/dashboard/shared/settings'
    | '/dashboard/teacher/analytics'
    | '/dashboard/teacher/observations'
    | '/dashboard/teacher/report'
    | '/dashboard/teacher/resources'
    | '/dashboard/therapist/analytics'
    | '/dashboard/therapist/report'
    | '/dashboard/therapist/resources'
    | '/dashboard/therapist/sessions'
    | '/dashboard/parent'
    | '/dashboard/teacher'
    | '/dashboard/therapist'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/data/$action'
    | '/dashboard/admin/community'
    | '/dashboard/admin/resources'
    | '/dashboard/admin/users'
    | '/dashboard/child/achievements'
    | '/dashboard/child/emotion'
    | '/dashboard/child/journey'
    | '/dashboard/child/mission'
    | '/dashboard/child/simulation'
    | '/dashboard/child/story'
    | '/dashboard/parent/analytics'
    | '/dashboard/parent/children'
    | '/dashboard/parent/report'
    | '/dashboard/parent/resources'
    | '/dashboard/shared/community'
    | '/dashboard/shared/settings'
    | '/dashboard/teacher/analytics'
    | '/dashboard/teacher/observations'
    | '/dashboard/teacher/report'
    | '/dashboard/teacher/resources'
    | '/dashboard/therapist/analytics'
    | '/dashboard/therapist/report'
    | '/dashboard/therapist/resources'
    | '/dashboard/therapist/sessions'
    | '/dashboard/parent/'
    | '/dashboard/teacher/'
    | '/dashboard/therapist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDataActionRoute: typeof ApiDataActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/therapist/': {
      id: '/dashboard/therapist/'
      path: '/therapist'
      fullPath: '/dashboard/therapist/'
      preLoaderRoute: typeof DashboardTherapistIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teacher/': {
      id: '/dashboard/teacher/'
      path: '/teacher'
      fullPath: '/dashboard/teacher/'
      preLoaderRoute: typeof DashboardTeacherIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parent/': {
      id: '/dashboard/parent/'
      path: '/parent'
      fullPath: '/dashboard/parent/'
      preLoaderRoute: typeof DashboardParentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/therapist/sessions': {
      id: '/dashboard/therapist/sessions'
      path: '/therapist/sessions'
      fullPath: '/dashboard/therapist/sessions'
      preLoaderRoute: typeof DashboardTherapistSessionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/therapist/resources': {
      id: '/dashboard/therapist/resources'
      path: '/therapist/resources'
      fullPath: '/dashboard/therapist/resources'
      preLoaderRoute: typeof DashboardTherapistResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/therapist/report': {
      id: '/dashboard/therapist/report'
      path: '/therapist/report'
      fullPath: '/dashboard/therapist/report'
      preLoaderRoute: typeof DashboardTherapistReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/therapist/analytics': {
      id: '/dashboard/therapist/analytics'
      path: '/therapist/analytics'
      fullPath: '/dashboard/therapist/analytics'
      preLoaderRoute: typeof DashboardTherapistAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teacher/resources': {
      id: '/dashboard/teacher/resources'
      path: '/teacher/resources'
      fullPath: '/dashboard/teacher/resources'
      preLoaderRoute: typeof DashboardTeacherResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teacher/report': {
      id: '/dashboard/teacher/report'
      path: '/teacher/report'
      fullPath: '/dashboard/teacher/report'
      preLoaderRoute: typeof DashboardTeacherReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teacher/observations': {
      id: '/dashboard/teacher/observations'
      path: '/teacher/observations'
      fullPath: '/dashboard/teacher/observations'
      preLoaderRoute: typeof DashboardTeacherObservationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/teacher/analytics': {
      id: '/dashboard/teacher/analytics'
      path: '/teacher/analytics'
      fullPath: '/dashboard/teacher/analytics'
      preLoaderRoute: typeof DashboardTeacherAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shared/settings': {
      id: '/dashboard/shared/settings'
      path: '/shared/settings'
      fullPath: '/dashboard/shared/settings'
      preLoaderRoute: typeof DashboardSharedSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shared/community': {
      id: '/dashboard/shared/community'
      path: '/shared/community'
      fullPath: '/dashboard/shared/community'
      preLoaderRoute: typeof DashboardSharedCommunityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parent/resources': {
      id: '/dashboard/parent/resources'
      path: '/parent/resources'
      fullPath: '/dashboard/parent/resources'
      preLoaderRoute: typeof DashboardParentResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parent/report': {
      id: '/dashboard/parent/report'
      path: '/parent/report'
      fullPath: '/dashboard/parent/report'
      preLoaderRoute: typeof DashboardParentReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parent/children': {
      id: '/dashboard/parent/children'
      path: '/parent/children'
      fullPath: '/dashboard/parent/children'
      preLoaderRoute: typeof DashboardParentChildrenRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parent/analytics': {
      id: '/dashboard/parent/analytics'
      path: '/parent/analytics'
      fullPath: '/dashboard/parent/analytics'
      preLoaderRoute: typeof DashboardParentAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/story': {
      id: '/dashboard/child/story'
      path: '/child/story'
      fullPath: '/dashboard/child/story'
      preLoaderRoute: typeof DashboardChildStoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/simulation': {
      id: '/dashboard/child/simulation'
      path: '/child/simulation'
      fullPath: '/dashboard/child/simulation'
      preLoaderRoute: typeof DashboardChildSimulationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/mission': {
      id: '/dashboard/child/mission'
      path: '/child/mission'
      fullPath: '/dashboard/child/mission'
      preLoaderRoute: typeof DashboardChildMissionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/journey': {
      id: '/dashboard/child/journey'
      path: '/child/journey'
      fullPath: '/dashboard/child/journey'
      preLoaderRoute: typeof DashboardChildJourneyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/emotion': {
      id: '/dashboard/child/emotion'
      path: '/child/emotion'
      fullPath: '/dashboard/child/emotion'
      preLoaderRoute: typeof DashboardChildEmotionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/child/achievements': {
      id: '/dashboard/child/achievements'
      path: '/child/achievements'
      fullPath: '/dashboard/child/achievements'
      preLoaderRoute: typeof DashboardChildAchievementsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/resources': {
      id: '/dashboard/admin/resources'
      path: '/admin/resources'
      fullPath: '/dashboard/admin/resources'
      preLoaderRoute: typeof DashboardAdminResourcesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/community': {
      id: '/dashboard/admin/community'
      path: '/admin/community'
      fullPath: '/dashboard/admin/community'
      preLoaderRoute: typeof DashboardAdminCommunityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/data/$action': {
      id: '/api/data/$action'
      path: '/api/data/$action'
      fullPath: '/api/data/$action'
      preLoaderRoute: typeof ApiDataActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminCommunityRoute: typeof DashboardAdminCommunityRoute
  DashboardAdminResourcesRoute: typeof DashboardAdminResourcesRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardChildAchievementsRoute: typeof DashboardChildAchievementsRoute
  DashboardChildEmotionRoute: typeof DashboardChildEmotionRoute
  DashboardChildJourneyRoute: typeof DashboardChildJourneyRoute
  DashboardChildMissionRoute: typeof DashboardChildMissionRoute
  DashboardChildSimulationRoute: typeof DashboardChildSimulationRoute
  DashboardChildStoryRoute: typeof DashboardChildStoryRoute
  DashboardParentAnalyticsRoute: typeof DashboardParentAnalyticsRoute
  DashboardParentChildrenRoute: typeof DashboardParentChildrenRoute
  DashboardParentReportRoute: typeof DashboardParentReportRoute
  DashboardParentResourcesRoute: typeof DashboardParentResourcesRoute
  DashboardSharedCommunityRoute: typeof DashboardSharedCommunityRoute
  DashboardSharedSettingsRoute: typeof DashboardSharedSettingsRoute
  DashboardTeacherAnalyticsRoute: typeof DashboardTeacherAnalyticsRoute
  DashboardTeacherObservationsRoute: typeof DashboardTeacherObservationsRoute
  DashboardTeacherReportRoute: typeof DashboardTeacherReportRoute
  DashboardTeacherResourcesRoute: typeof DashboardTeacherResourcesRoute
  DashboardTherapistAnalyticsRoute: typeof DashboardTherapistAnalyticsRoute
  DashboardTherapistReportRoute: typeof DashboardTherapistReportRoute
  DashboardTherapistResourcesRoute: typeof DashboardTherapistResourcesRoute
  DashboardTherapistSessionsRoute: typeof DashboardTherapistSessionsRoute
  DashboardParentIndexRoute: typeof DashboardParentIndexRoute
  DashboardTeacherIndexRoute: typeof DashboardTeacherIndexRoute
  DashboardTherapistIndexRoute: typeof DashboardTherapistIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminCommunityRoute: DashboardAdminCommunityRoute,
  DashboardAdminResourcesRoute: DashboardAdminResourcesRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardChildAchievementsRoute: DashboardChildAchievementsRoute,
  DashboardChildEmotionRoute: DashboardChildEmotionRoute,
  DashboardChildJourneyRoute: DashboardChildJourneyRoute,
  DashboardChildMissionRoute: DashboardChildMissionRoute,
  DashboardChildSimulationRoute: DashboardChildSimulationRoute,
  DashboardChildStoryRoute: DashboardChildStoryRoute,
  DashboardParentAnalyticsRoute: DashboardParentAnalyticsRoute,
  DashboardParentChildrenRoute: DashboardParentChildrenRoute,
  DashboardParentReportRoute: DashboardParentReportRoute,
  DashboardParentResourcesRoute: DashboardParentResourcesRoute,
  DashboardSharedCommunityRoute: DashboardSharedCommunityRoute,
  DashboardSharedSettingsRoute: DashboardSharedSettingsRoute,
  DashboardTeacherAnalyticsRoute: DashboardTeacherAnalyticsRoute,
  DashboardTeacherObservationsRoute: DashboardTeacherObservationsRoute,
  DashboardTeacherReportRoute: DashboardTeacherReportRoute,
  DashboardTeacherResourcesRoute: DashboardTeacherResourcesRoute,
  DashboardTherapistAnalyticsRoute: DashboardTherapistAnalyticsRoute,
  DashboardTherapistReportRoute: DashboardTherapistReportRoute,
  DashboardTherapistResourcesRoute: DashboardTherapistResourcesRoute,
  DashboardTherapistSessionsRoute: DashboardTherapistSessionsRoute,
  DashboardParentIndexRoute: DashboardParentIndexRoute,
  DashboardTeacherIndexRoute: DashboardTeacherIndexRoute,
  DashboardTherapistIndexRoute: DashboardTherapistIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDataActionRoute: ApiDataActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
